services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA1_HOST_PORT}:${KAFKA1_CONTAINER_PORT}"
    volumes:
      - kafka1-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA1_CONTAINER_PORT},PLAINTEXT_HOST://0.0.0.0:${KAFKA1_HOST_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:${KAFKA1_CONTAINER_PORT},PLAINTEXT_HOST://${KAFKA1_ADVERTISED_HOST}:${KAFKA1_HOST_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA2_HOST_PORT}:${KAFKA2_CONTAINER_PORT}"
    volumes:
      - kafka2-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA2_CONTAINER_PORT},PLAINTEXT_HOST://0.0.0.0:${KAFKA2_HOST_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:${KAFKA2_CONTAINER_PORT},PLAINTEXT_HOST://${KAFKA2_ADVERTISED_HOST}:${KAFKA2_HOST_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA3_HOST_PORT}:${KAFKA3_CONTAINER_PORT}"
    volumes:
      - kafka3-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA3_CONTAINER_PORT},PLAINTEXT_HOST://0.0.0.0:${KAFKA3_HOST_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:${KAFKA3_CONTAINER_PORT},PLAINTEXT_HOST://${KAFKA3_ADVERTISED_HOST}:${KAFKA3_HOST_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
